version: "3.9"

volumes:
  redis-data:
  static-data:

services:
  redis:
    image: redislabs/redismod:latest
    ports:
      - 6379:6379
    volumes:
      - redis-data:/data

  ui:
    restart: always
    build:
      context: .
      args: &environment
        API_URL: https://qdo.quid.io/api
        USDT_CONTRACT_ID: "0xdAC17F958D2ee523a2206206994597C13D831ec7"
        CONTRACT_ID: "0xA0Dc23FA9F42146E62E027C50f866d8Bdcc46a8a"
        NETWOKR: mainnet
        INFURA_KEY: "f10e928c34314bdeb7198c2e738f3efa"
    environment:
      REDIS_CONNECTION_STRING: redis://redis/0
      NEXT_PUBLIC_CONTRACT_ID: "0xA0Dc23FA9F42146E62E027C50f866d8Bdcc46a8a"
      NEXT_PUBLIC_INFURA_KEY: "f10e928c34314bdeb7198c2e738f3efa"
      NEXT_PUBLIC_USDT_CONTRACT_ID: "0xdAC17F958D2ee523a2206206994597C13D831ec7"
      NEXT_PUBLIC_API_URL: https://qdo.quid.io/api
      NEXT_PUBLIC_NETWOKR: mainnet
      NEXT_PUBLIC_OWNER_ID: 0x42cc020Ef5e9681364ABB5aba26F39626F1874A4

    ports:
      - "3000:3000"
    depends_on:
      - redis
    volumes:
      - static-data:/static-data:rw

  nginx:
    image: linuxserver/swag:1.20.0
    cap_add:
      - NET_ADMIN
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=UTC
      - URL=qdo.quid.io
      - VALIDATION=http
      - STAGING=false
    ports:
      - 443:443
      - 80:80
    restart: unless-stopped
    volumes:
      - "/home/ec2-user/qdo-app/docker/linuxserver/default:/config/nginx/site-confs/default"
      - static-data:/static-data
    depends_on:
      - ui
