// This file was generated by script

import arrowDown from './arrow-down.svg';
import close from './close.svg';
import email from './email.svg';
import github from './github.svg';
import information from './information.svg';
import musicWave from './music-wave.svg';
import twitter from './twitter.svg';

const icons = {
  'arrow-down': arrowDown,
  close,
  email,
  github,
  information,
  'music-wave': musicWave,
  twitter,
};

export default icons;
